# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-24 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='Popularity',
            field=models.BooleanField(default=0),
        ),
    ]
