# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-25 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20180724_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childcategory',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='childcategory',
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(null=True, upload_to='upload'),
        ),
        migrations.DeleteModel(
            name='ChildCategory',
        ),
    ]
