# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-24 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_auto_20180723_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='Popularity',
            field=models.IntegerField(default=0),
        ),
    ]
